version: '3'
services:
  web:
    build: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - external-network
networks:
  external-network:
    internal: false
