version: '3'
services:
  web-alpha:
    build:
      context: .
      dockerfile: DockerfileAlpha
    ports:
      - '4173:4173'
    networks:
      - external-network
    environment:
      HOST: "0.0.0.0"
      PORT: 4173

  web-beta:
    build:
      context: .
      dockerfile: DockerfileBeta
    ports:
      - '4172:4172'
    networks:
      - external-network
    environment:
      HOST: "0.0.0.0"
      PORT: 4172

networks:
  external-network:
    driver: bridge
