version: '3'
services:
  web-alpha:
    build:
      context: .
      dockerfile: DockerfileAlpha
    ports:
      - '4173:4173'
    networks:
      - external-network

  web-beta:
    build:
      context: .
      dockerfile: DockerfileBeta
    ports:
      - '4172:4173'
    networks:
      - external-network

networks:
  external-network:
    internal: false
